### ISSUE TITLE
error

### ISSUE THREAD

**Issue by it-can** [spatie/macroable#26]
getting this error after updating

```
PHP Fatal error:  During class fetch: Uncaught ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /vendor/spatie/macroable/src/Macroable.php:14
```

**Comment by freekmurze** [comment]
Make sure you're on the right PHP version

**Comment by it-can** [comment]
7.4

**Comment by fredattack** [comment]
hello, 
I have exactly the same problem in docker with php:7.4-fpm-alpine.
If i use php:8.0-fpm-alpine everything work fine. 
can you help me?

**Comment by me-shaon** [comment]
@fredattack This package has dropped its support for `PHP 7` in v2. https://github.com/spatie/macroable/releases/tag/2.0.0
To make it work on PHP 7, you should use an earlier version of this package.

**Comment by aubreypwd** [comment]
Here's what I had to do: https://github.com/aubreypwd/wp-config-common/commit/99c36105bd4f2f2a47f899aa831a83b9ed10db24

Basically Composer was preferring 2.0 when requiring `spatie/ray` which wasn't working in PHP 7.4.

**Comment by aubreypwd** [comment]
Update: I ran into this issue again today and my fix above no longer worked.

```json
"platform": {
    "php": "7.4"
}
```

But, adding this to `composer.json` and doing `composer update` seemed to help using PHP 7.4
