### ISSUE TITLE
Unable to use ray on docker with PHP 7.4  (php:7.4.9-fpm-alpine image)

### ISSUE THREAD

**Issue by fredattack** [spatie/macroable#27]
Hi guys, 

I can't use ray in docker container when i use php version 7.4 (php:7.4.9-fpm-alpine), but i have'nt any problems with php version 8.0.

I really can't update all this project for php 8.0 .
Can you help me?? 
`
During class fetch: Uncaught ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/html/vendor/spatie/macroable/src/Macroable.php:14
Stack trace:
#0 /var/www/html/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/var/www/html/v...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Spatie\\Macroabl...')
#2 /var/www/html/vendor/spatie/ray/src/Ray.php(50): spl_autoload_call('Spatie\\Macroabl...')
#3 /var/www/html/vendor/composer/ClassLoader.php(480): include('/var/www/html/v...')
#4 /var/www/html/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/var/www/html/v...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('Spatie\\Ray\\Ray')
#6 /var/www/html/vendor/spatie/laravel-ray/src/Ray.php(41): spl_autoload_call('Spatie\\Ray\\Ray')
#7 /var/www/html/vendor/composer/ClassLoader.php(480): include('/var/www/html/v...')`

**Comment by freekmurze** [comment]
The package doesn't contain a syntax error. It seems you're not using PHP 8.

**Comment by fredattack** [comment]
hi freek,

No i dont use PHP 8 it's 7.4 but the requirements for Ray is PHP 7 and no PHP 8 .

**Comment by Muffinman** [comment]
I just got hit by this one as well.

From the looks of Ray's [composer.json](https://github.com/spatie/ray/blob/main/composer.json) you could probably require `spatie/macroable` at `^1.0.1` and Ray should still work.
