### ISSUE TITLE
What is the usecase?

### ISSUE THREAD

**Issue by robbertstevens** [spatie/macroable#6]
Hey guys!

Not sure if this is the right place for this but I am really interested for use cases you encountered where you want this.

The idea itself is very interesting.

**Comment by freekmurze** [comment]
Keep an eye on my blog,  I'll write about about the use case at `https://murze.be` soon.

Shortly said this package is targeted at package maintainers that want to enable their users to add new methods without changing the package itself.

**Comment by drupol** [comment]
Hi Freek, Robbert,

I've discovered this way of working very recently, when I started to use [peridot-php/leo](https://github.com/peridot-php/leo).

I was looking into the library to see how they did and I discovered all of this, this is why I had, just like Freek, to create such a library. But I'm not here to promote it of course.

Leo's extending mechanism is very nice and doesn't force you to create and object and inject it in it to use it. Each Leo's library's method is actually stored in a variable (_quickly said_). You can modify them and extend it by adding dynamic methods.

I'm still discovering all of this and I'm sure that it will have a lot of applications very soon :-)

Have a good day fellas!
